using System;
using System.Collections.Generic;

namespace RezoraData.Models
{
    public partial class MlsIncomeListings
    {
        public string OrgId { get; set; }
        public string ListingId { get; set; }
        public string AdArea { get; set; }
        public string AdBlockNumber { get; set; }
        public string AdCityName { get; set; }
        public string AdCountyCode { get; set; }
        public int? AdCountyFips { get; set; }
        public string AdCrossStreets { get; set; }
        public string AdDirections { get; set; }
        public string AdGeoCityName { get; set; }
        public string AdGeoState { get; set; }
        public string AdGeoStreetDesignator { get; set; }
        public string AdGeoStreetDirection { get; set; }
        public string AdGeoStreetName { get; set; }
        public string AdGeoStreetNumber { get; set; }
        public string AdGeoStreetPostDir { get; set; }
        public string AdGeoStreetPreType { get; set; }
        public string AdGeoStreetUnitType { get; set; }
        public string AdGeoStreetZip4 { get; set; }
        public string AdGeoUnit { get; set; }
        public string AdGeoZipCode { get; set; }
        public float InLatitude { get; set; }
        public float InLongitude { get; set; }
        public string AdLotNumber { get; set; }
        public string AdMapCode { get; set; }
        public byte? AdMapPrecision { get; set; }
        public string AdMarketingArea { get; set; }
        public string AdNeighborhood { get; set; }
        public string AdParcelNumber { get; set; }
        public string AdPostalCode { get; set; }
        public string AdState { get; set; }
        public string AdStreetDesignator { get; set; }
        public string AdStreetDirection { get; set; }
        public string AdStreetName { get; set; }
        public int? AdStreetNumber { get; set; }
        public string AdStreetPostDir { get; set; }
        public string AdStreetPreType { get; set; }
        public string AdStreetUnitType { get; set; }
        public string AdStreetZip4 { get; set; }
        public string AdTractNumber { get; set; }
        public string AdUnit { get; set; }
        public string AdZipCode { get; set; }
        public string AdZoneFeatures { get; set; }
        public string AgCoagentId { get; set; }
        public string AgCoagentName { get; set; }
        public string AgCoagentPhone { get; set; }
        public string AgEmail { get; set; }
        public string AgFax { get; set; }
        public string AgId { get; set; }
        public string AgMayRepresentSellerAndBuyer { get; set; }
        public string AgMobilePhone { get; set; }
        public string AgName { get; set; }
        public string AgOfficeEmail { get; set; }
        public string AgOfficeId { get; set; }
        public string AgOfficeName { get; set; }
        public string AgOfficePhone { get; set; }
        public string AgPager { get; set; }
        public string AgPhone { get; set; }
        public string AgReciprocalLink { get; set; }
        public string AgRemarks { get; set; }
        public string AgRepresentationFeatures { get; set; }
        public string AgVmail { get; set; }
        public string AgWebsite { get; set; }
        public string ExFldZoneYn { get; set; }
        public string ExLocationFeatures { get; set; }
        public decimal? ExLotSizeAcres { get; set; }
        public string ExLotSizeDimensions { get; set; }
        public string ExLotSizeFeatures { get; set; }
        public string ExLotSizeSource { get; set; }
        public int? ExLotSizeSquareFeet { get; set; }
        public string ExLotsizeRange { get; set; }
        public string ExParkingFeatures { get; set; }
        public byte? ExParkingSpaces { get; set; }
        public byte? ExParkingSpacesTotal { get; set; }
        public string ExRoadFeatures { get; set; }
        public string ExSewerFeatures { get; set; }
        public string ExStyle { get; set; }
        public string ExViewFeatures { get; set; }
        public string ExWateraccessFeatures { get; set; }
        public string ExWaterfrontFeatures { get; set; }
        public string FiAdditionalFinanceInfo { get; set; }
        public string FiCompTrigger { get; set; }
        public string FiFinanceFeatures { get; set; }
        public string FiFinanceSponsor { get; set; }
        public string FiFinanceTerms { get; set; }
        public decimal? FiFirstTrustDeedAmount { get; set; }
        public string FiFirstTrustDeedAssumable { get; set; }
        public DateTime? FiFirstTrustDeedDue { get; set; }
        public decimal? FiFirstTrustDeedFee { get; set; }
        public decimal? FiFirstTrustDeedInterest { get; set; }
        public string FiFirstTrustDeedLender { get; set; }
        public string FiFirstTrustDeedRate { get; set; }
        public string FiFirstTrustDeedType { get; set; }
        public decimal? FiGrossEquity { get; set; }
        public string FiIgnoreCompTrigger { get; set; }
        public string FiIgnorePaidYn { get; set; }
        public string FiPossession { get; set; }
        public decimal? FiSecondTrustDeedAmount { get; set; }
        public string FiSecondTrustDeedAssumable { get; set; }
        public DateTime? FiSecondTrustDeedDue { get; set; }
        public decimal? FiSecondTrustDeedFee { get; set; }
        public decimal? FiSecondTrustDeedInterest { get; set; }
        public string FiSecondTrustDeedLender { get; set; }
        public string FiSecondTrustDeedRate { get; set; }
        public string FiSecondTrustDeedType { get; set; }
        public decimal? FiTaxAmount { get; set; }
        public string FiTaxDescriptionFeatures { get; set; }
        public byte? FiTaxPeriod { get; set; }
        public decimal? FiTotalTaxRate { get; set; }
        public string IfLevelsFeatures { get; set; }
        public string IfSpecialFeatures { get; set; }
        public string IfUtilitiesFeatures { get; set; }
        public string IfWaterFeatures { get; set; }
        public string InAdditionalPicturesYn { get; set; }
        public int? InAdom { get; set; }
        public string InApNumber { get; set; }
        public decimal? InAssociationDues1 { get; set; }
        public decimal? InAssociationDues2 { get; set; }
        public string InAssociationFeatures { get; set; }
        public string InAssociationLitigationYn { get; set; }
        public byte? InAssociationPeriod { get; set; }
        public string InAssociationPhone { get; set; }
        public string InAssociationYn { get; set; }
        public DateTime? InCloseDate { get; set; }
        public string InCompensationBuyAgent { get; set; }
        public string InCompensationNonrep { get; set; }
        public string InCompensationTransactionAgent { get; set; }
        public string InDetailUrl { get; set; }
        public DateTime? InEscrowDate { get; set; }
        public string InExclusions { get; set; }
        public byte? InImageCount { get; set; }
        public string InLastTransactionCode { get; set; }
        public decimal? InLeaseAmount { get; set; }
        public byte? InLeasePeriod { get; set; }
        public string InLeaseOptionYn { get; set; }
        public byte? InLeaseTerm { get; set; }
        public string InLegalDescription { get; set; }
        public string InLegalFeatures { get; set; }
        public DateTime? InListDate { get; set; }
        public decimal? InListPrice { get; set; }
        public string InListPriceExclusionRemarks { get; set; }
        public string InListingAgreementType { get; set; }
        public string InListingHasForSaleSignYn { get; set; }
        public short? InListingLoadedByBroker { get; set; }
        public DateTime? InLoadDate { get; set; }
        public DateTime? InModifyDate { get; set; }
        public DateTime? InOffmarketDate { get; set; }
        public decimal? InOrigListPrice { get; set; }
        public string InOwnerName { get; set; }
        public string InOwnerPhone { get; set; }
        public DateTime? InPendingDate { get; set; }
        public decimal? InPendingPrice { get; set; }
        public decimal? InPreviousListPrice { get; set; }
        public string InPreviousStatus { get; set; }
        public DateTime? InProjectedEscrowCloseDate { get; set; }
        public string InPropertyType { get; set; }
        public string InPublicRemarks { get; set; }
        public DateTime? InPullDate { get; set; }
        public decimal? InRangeHighPrice { get; set; }
        public decimal? InRangeLowPrice { get; set; }
        public string InRangePriceFlag { get; set; }
        public string InReciprocalListing { get; set; }
        public string InRestrictions { get; set; }
        public string InSellerAgreesToPayPoints { get; set; }
        public decimal? InSellingOfficeComp { get; set; }
        public string InSellingOfficeCompType { get; set; }
        public string InSellingOfficeCompensation { get; set; }
        public string InShowingInstructions { get; set; }
        public string InSoldAgentName { get; set; }
        public string InSoldAgentOfficeId { get; set; }
        public string InSoldAgentPublicId { get; set; }
        public DateTime? InSoldDate { get; set; }
        public string InSoldFinanceTerms { get; set; }
        public string InSoldOfficeName { get; set; }
        public decimal? InSoldPrice { get; set; }
        public string InSoldTerms { get; set; }
        public string InStatus { get; set; }
        public DateTime? InStatusDate { get; set; }
        public string InSubtype { get; set; }
        public DateTime? InSystemExpireDate { get; set; }
        public decimal? InTotalAssessedValue { get; set; }
        public string InTractCode { get; set; }
        public string InTractName { get; set; }
        public DateTime? InTransactDate { get; set; }
        public string InTransferOfPossession { get; set; }
        public string InViewYn { get; set; }
        public string InVirtualTourLink { get; set; }
        public DateTime? InWithdrawnDate { get; set; }
        public string RegMlsCode { get; set; }
        public string ScElementarySchool { get; set; }
        public string ScHighSchool { get; set; }
        public string ScJuniorHighSchool { get; set; }
        public string ScSchoolDistrict { get; set; }
        public string ListOnInternetYn { get; set; }
        public string DisplayAddressYn { get; set; }
        public string ListingIddYn { get; set; }
        public string DisplayDistressedPropertyYn { get; set; }
        public string InDistressType { get; set; }
        public string ExBuildingCondition { get; set; }
        public string ExBuildingFaces { get; set; }
        public decimal? ExBuildingSquareFeet { get; set; }
        public byte? ExCarportSpaces { get; set; }
        public string ExConstructionFeatures { get; set; }
        public string ExFenceFeatures { get; set; }
        public string ExFoundationFeatures { get; set; }
        public string ExGarageFeatures { get; set; }
        public short? ExGarageRemotes { get; set; }
        public byte? ExGarageSpaces { get; set; }
        public string ExGarageType { get; set; }
        public string ExGeneralFeatures { get; set; }
        public string ExGolfFeatures { get; set; }
        public string ExHorsePropertyFeatures { get; set; }
        public string ExPatioDimensions { get; set; }
        public string ExPatioFeatures { get; set; }
        public string ExPatioYn { get; set; }
        public string ExPoolDimensions { get; set; }
        public string ExPoolFeatures { get; set; }
        public string ExPoolYn { get; set; }
        public string ExRoofFeatures { get; set; }
        public string ExRvParkingDimensions { get; set; }
        public string ExSpaFeatures { get; set; }
        public string ExSpaYn { get; set; }
        public string ExSprinklerFeatures { get; set; }
        public string ExStyleFeatures { get; set; }
        public string ExSubdivisionFeatures { get; set; }
        public string ExWaterstructuresFeatures { get; set; }
        public decimal? FiCapRate { get; set; }
        public decimal? FiGaragesIncome { get; set; }
        public decimal? FiGrossMultiplier { get; set; }
        public decimal? FiGrossOperIncome { get; set; }
        public decimal? FiGrossSchedIncome { get; set; }
        public decimal? FiGrossSpendIncome { get; set; }
        public decimal? FiImprovDollars { get; set; }
        public decimal? FiImprovPct { get; set; }
        public decimal? FiLandDollars { get; set; }
        public string FiLandFeeLeaseYn { get; set; }
        public decimal? FiLandRate { get; set; }
        public decimal? FiLaundryIncome { get; set; }
        public decimal? FiLeaseAmtPerYear { get; set; }
        public string FiLeaseMoYr { get; set; }
        public DateTime? FiLeaseYerExpires { get; set; }
        public decimal? FiLoanPayment { get; set; }
        public decimal? FiMaintDollars { get; set; }
        public decimal? FiMaintPct { get; set; }
        public decimal? FiMoGrossSchInc { get; set; }
        public decimal? FiNetIncome { get; set; }
        public decimal? FiNewTaxes { get; set; }
        public decimal? FiOperatingExp { get; set; }
        public decimal? FiOperatingPct { get; set; }
        public decimal? FiOtherExpAmt { get; set; }
        public string FiOtherIncome { get; set; }
        public string FiOtherIncomeDesc { get; set; }
        public decimal? FiPerPropDollars { get; set; }
        public decimal? FiPerPropRate { get; set; }
        public decimal? FiPoolExpense { get; set; }
        public decimal? FiPricePerUnit { get; set; }
        public string FiProfMgmtYn { get; set; }
        public string FiTaxArea { get; set; }
        public decimal? FiTotalActualRent { get; set; }
        public decimal? FiTotalExpense { get; set; }
        public decimal? FiTotalTaxes { get; set; }
        public string FiWorkmanComp { get; set; }
        public string IfApplianceFeatures { get; set; }
        public string IfBasementFeatures { get; set; }
        public string IfCoolingFeatures { get; set; }
        public string IfCoolingYn { get; set; }
        public string IfEnergyFeatures { get; set; }
        public string IfFireplaceFeatures { get; set; }
        public byte? IfFireplaceNumber { get; set; }
        public string IfFireplaceYn { get; set; }
        public string IfFloorFeatures { get; set; }
        public string IfGeneralFeatures { get; set; }
        public string IfHeatingFeatures { get; set; }
        public string IfLevels { get; set; }
        public string IfPetFeatures { get; set; }
        public string IfPlumbingFeatures { get; set; }
        public string IfSecurityFeatures { get; set; }
        public string IfSecuritySystemYn { get; set; }
        public string IfWindowFeatures { get; set; }
        public string InAdditionsAlter { get; set; }
        public string InAgeFeatures { get; set; }
        public decimal? InAvgSqft1br { get; set; }
        public decimal? InAvgSqft2br { get; set; }
        public decimal? InAvgSqft3br { get; set; }
        public decimal? InAvgSqftStudio { get; set; }
        public string InBldgPermit { get; set; }
        public string InBuilderName { get; set; }
        public string InCableTvYn { get; set; }
        public int? InCarports { get; set; }
        public string InCoastalZoneYn { get; set; }
        public string InFloodZoneYn { get; set; }
        public int? InGarageNoRented { get; set; }
        public decimal? InGarageRentRate { get; set; }
        public int? InGaragesNo { get; set; }
        public string InGardenerYn { get; set; }
        public string InIsAttached { get; set; }
        public string InKeyboxFeatures { get; set; }
        public string InKeyboxLocation { get; set; }
        public string InLaundryEqmtYn { get; set; }
        public string InManagerSalary { get; set; }
        public int? InNumUnitsLeased { get; set; }
        public int? InNumberPatio { get; set; }
        public int? InNumberUnits { get; set; }
        public string InOtherExpDesc { get; set; }
        public string InPestControlYn { get; set; }
        public string InRecRoomYn { get; set; }
        public DateTime? InRemodeledDate { get; set; }
        public string InRentControlYn { get; set; }
        public string InSepMtrElecYn { get; set; }
        public string InSepMtrGasYn { get; set; }
        public string InSepMtrWaterYn { get; set; }
        public string InSlideZoneYn { get; set; }
        public string InTenantPaysCableYn { get; set; }
        public string InTenantPaysElecYn { get; set; }
        public string InTenantPaysGasYn { get; set; }
        public string InTenantPaysTrashYn { get; set; }
        public string InTenantPaysWaterYn { get; set; }
        public decimal? InTotalBldgSqft { get; set; }
        public int? InTotalBldgs { get; set; }
        public short? InTotalUnitsInComplex { get; set; }
        public string InTrashYn { get; set; }
        public string InVolt220OutletLocation { get; set; }
        public short? InYearBuilt { get; set; }
        public string RmBathroomFeatures { get; set; }
        public byte? RmBathsFull { get; set; }
        public byte? RmBathsHalf { get; set; }
        public byte? RmBathsQuarter { get; set; }
        public byte? RmBathsThreeQuarter { get; set; }
        public decimal? RmBathsTotal { get; set; }
        public string RmBedroomFeatures { get; set; }
        public byte? RmBedroomsTotal { get; set; }
        public string RmBonusFeatures { get; set; }
        public string RmBonusYn { get; set; }
        public string RmDenYn { get; set; }
        public string RmDiningFeatures { get; set; }
        public string RmFamilyYn { get; set; }
        public string RmFormalDiningYn { get; set; }
        public string RmGeneralFeatures { get; set; }
        public string RmKitchenFeatures { get; set; }
        public string RmLaundryFeatures { get; set; }
        public string RmLivingFeatures { get; set; }
        public string RmLivingYn { get; set; }
        public string RmMasterDressingAreaYn { get; set; }
        public string RmMasterYn { get; set; }
        public int? RmRoomsTotal { get; set; }
        public string RmTermiteClearYn { get; set; }
        public string RmUtilityFeatures { get; set; }
        public byte? RmWalkInClosets { get; set; }
        public decimal? Un1ActualRent { get; set; }
        public string Un1FurnishedYn { get; set; }
        public decimal? Un1NumberBaths { get; set; }
        public decimal? Un1NumberBeds { get; set; }
        public decimal? Un1NumberUnits { get; set; }
        public decimal? Un1TotalRent { get; set; }
        public decimal? Un10ActualRent { get; set; }
        public string Un10FurnishedYn { get; set; }
        public decimal? Un10NumberBaths { get; set; }
        public decimal? Un10NumberBeds { get; set; }
        public decimal? Un10NumberUnits { get; set; }
        public decimal? Un10TotalRent { get; set; }
        public decimal? Un11ActualRent { get; set; }
        public string Un11FurnishedYn { get; set; }
        public decimal? Un11NumberBaths { get; set; }
        public decimal? Un11NumberBeds { get; set; }
        public decimal? Un11NumberUnits { get; set; }
        public decimal? Un11TotalRent { get; set; }
        public decimal? Un12ActualRent { get; set; }
        public string Un12FurnishedYn { get; set; }
        public decimal? Un12NumberBaths { get; set; }
        public decimal? Un12NumberBeds { get; set; }
        public decimal? Un12NumberUnits { get; set; }
        public decimal? Un12TotalRent { get; set; }
        public decimal? Un13ActualRent { get; set; }
        public string Un13FurnishedYn { get; set; }
        public decimal? Un13NumberBaths { get; set; }
        public decimal? Un13NumberBeds { get; set; }
        public decimal? Un13NumberUnits { get; set; }
        public decimal? Un13TotalRent { get; set; }
        public decimal? Un2ActualRent { get; set; }
        public string Un2FurnishedYn { get; set; }
        public decimal? Un2NumberBaths { get; set; }
        public decimal? Un2NumberBeds { get; set; }
        public decimal? Un2NumberUnits { get; set; }
        public decimal? Un2TotalRent { get; set; }
        public decimal? Un3ActualRent { get; set; }
        public string Un3FurnishedYn { get; set; }
        public decimal? Un3NumberBaths { get; set; }
        public decimal? Un3NumberBeds { get; set; }
        public decimal? Un3NumberUnits { get; set; }
        public decimal? Un3TotalRent { get; set; }
        public decimal? Un4ActualRent { get; set; }
        public string Un4FurnishedYn { get; set; }
        public decimal? Un4NumberBaths { get; set; }
        public decimal? Un4NumberBeds { get; set; }
        public decimal? Un4NumberUnits { get; set; }
        public decimal? Un4TotalRent { get; set; }
        public decimal? Un5ActualRent { get; set; }
        public string Un5FurnishedYn { get; set; }
        public decimal? Un5NumberBaths { get; set; }
        public decimal? Un5NumberBeds { get; set; }
        public decimal? Un5NumberUnits { get; set; }
        public decimal? Un5TotalRent { get; set; }
        public decimal? Un6ActualRent { get; set; }
        public string Un6FurnishedYn { get; set; }
        public decimal? Un6NumberBaths { get; set; }
        public decimal? Un6NumberBeds { get; set; }
        public decimal? Un6NumberUnits { get; set; }
        public decimal? Un6TotalRent { get; set; }
        public decimal? Un7ActualRent { get; set; }
        public string Un7FurnishedYn { get; set; }
        public decimal? Un7NumberBaths { get; set; }
        public decimal? Un7NumberBeds { get; set; }
        public decimal? Un7NumberUnits { get; set; }
        public decimal? Un7TotalRent { get; set; }
        public decimal? Un8ActualRent { get; set; }
        public string Un8FurnishedYn { get; set; }
        public decimal? Un8NumberBaths { get; set; }
        public decimal? Un8NumberBeds { get; set; }
        public decimal? Un8NumberUnits { get; set; }
        public decimal? Un8TotalRent { get; set; }
        public decimal? Un9ActualRent { get; set; }
        public string Un9FurnishedYn { get; set; }
        public decimal? Un9NumberBaths { get; set; }
        public decimal? Un9NumberBeds { get; set; }
        public decimal? Un9NumberUnits { get; set; }
        public decimal? Un9TotalRent { get; set; }
        public int? PublishStatus { get; set; }
        public DateTimeOffset LastUpdate { get; set; }
        public int LastImport { get; set; }
    }
}
