using System;
using System.Collections.Generic;

namespace RezoraData.Models
{
    public partial class MlsLeaseListings
    {
        public string OrgId { get; set; }
        public string ListingId { get; set; }
        public string AdArea { get; set; }
        public string AdBlockNumber { get; set; }
        public string AdCityName { get; set; }
        public string AdCountyCode { get; set; }
        public int? AdCountyFips { get; set; }
        public string AdCrossStreets { get; set; }
        public string AdDirections { get; set; }
        public string AdGeoCityName { get; set; }
        public string AdGeoState { get; set; }
        public string AdGeoStreetDesignator { get; set; }
        public string AdGeoStreetDirection { get; set; }
        public string AdGeoStreetName { get; set; }
        public string AdGeoStreetNumber { get; set; }
        public string AdGeoStreetPostDir { get; set; }
        public string AdGeoStreetPreType { get; set; }
        public string AdGeoStreetUnitType { get; set; }
        public string AdGeoStreetZip4 { get; set; }
        public string AdGeoUnit { get; set; }
        public string AdGeoZipCode { get; set; }
        public float InLatitude { get; set; }
        public float InLongitude { get; set; }
        public string AdLotNumber { get; set; }
        public string AdMapCode { get; set; }
        public byte? AdMapPrecision { get; set; }
        public string AdMarketingArea { get; set; }
        public string AdNeighborhood { get; set; }
        public string AdParcelNumber { get; set; }
        public string AdPostalCode { get; set; }
        public string AdState { get; set; }
        public string AdStreetDesignator { get; set; }
        public string AdStreetDirection { get; set; }
        public string AdStreetName { get; set; }
        public int? AdStreetNumber { get; set; }
        public string AdStreetPostDir { get; set; }
        public string AdStreetPreType { get; set; }
        public string AdStreetUnitType { get; set; }
        public string AdStreetZip4 { get; set; }
        public string AdTractNumber { get; set; }
        public string AdUnit { get; set; }
        public string AdZipCode { get; set; }
        public string AdZoneFeatures { get; set; }
        public string AgCoagentId { get; set; }
        public string AgCoagentName { get; set; }
        public string AgCoagentPhone { get; set; }
        public string AgEmail { get; set; }
        public string AgFax { get; set; }
        public string AgId { get; set; }
        public string AgMayRepresentSellerAndBuyer { get; set; }
        public string AgMobilePhone { get; set; }
        public string AgName { get; set; }
        public string AgOfficeEmail { get; set; }
        public string AgOfficeId { get; set; }
        public string AgOfficeName { get; set; }
        public string AgOfficePhone { get; set; }
        public string AgPager { get; set; }
        public string AgPhone { get; set; }
        public string AgReciprocalLink { get; set; }
        public string AgRemarks { get; set; }
        public string AgRepresentationFeatures { get; set; }
        public string AgVmail { get; set; }
        public string AgWebsite { get; set; }
        public string ExFldZoneYn { get; set; }
        public string ExLocationFeatures { get; set; }
        public decimal? ExLotSizeAcres { get; set; }
        public string ExLotSizeDimensions { get; set; }
        public string ExLotSizeFeatures { get; set; }
        public string ExLotSizeSource { get; set; }
        public int? ExLotSizeSquareFeet { get; set; }
        public string ExLotsizeRange { get; set; }
        public string ExParkingFeatures { get; set; }
        public byte? ExParkingSpaces { get; set; }
        public byte? ExParkingSpacesTotal { get; set; }
        public string ExRoadFeatures { get; set; }
        public string ExSewerFeatures { get; set; }
        public string ExStyle { get; set; }
        public string ExViewFeatures { get; set; }
        public string ExWateraccessFeatures { get; set; }
        public string ExWaterfrontFeatures { get; set; }
        public string FiAdditionalFinanceInfo { get; set; }
        public string FiCompTrigger { get; set; }
        public string FiFinanceFeatures { get; set; }
        public string FiFinanceSponsor { get; set; }
        public string FiFinanceTerms { get; set; }
        public decimal? FiFirstTrustDeedAmount { get; set; }
        public string FiFirstTrustDeedAssumable { get; set; }
        public DateTime? FiFirstTrustDeedDue { get; set; }
        public decimal? FiFirstTrustDeedFee { get; set; }
        public decimal? FiFirstTrustDeedInterest { get; set; }
        public string FiFirstTrustDeedLender { get; set; }
        public string FiFirstTrustDeedRate { get; set; }
        public string FiFirstTrustDeedType { get; set; }
        public decimal? FiGrossEquity { get; set; }
        public string FiIgnoreCompTrigger { get; set; }
        public string FiIgnorePaidYn { get; set; }
        public string FiPossession { get; set; }
        public decimal? FiSecondTrustDeedAmount { get; set; }
        public string FiSecondTrustDeedAssumable { get; set; }
        public DateTime? FiSecondTrustDeedDue { get; set; }
        public decimal? FiSecondTrustDeedFee { get; set; }
        public decimal? FiSecondTrustDeedInterest { get; set; }
        public string FiSecondTrustDeedLender { get; set; }
        public string FiSecondTrustDeedRate { get; set; }
        public string FiSecondTrustDeedType { get; set; }
        public decimal? FiTaxAmount { get; set; }
        public string FiTaxDescriptionFeatures { get; set; }
        public byte? FiTaxPeriod { get; set; }
        public decimal? FiTotalTaxRate { get; set; }
        public string IfLevelsFeatures { get; set; }
        public string IfSpecialFeatures { get; set; }
        public string IfUtilitiesFeatures { get; set; }
        public string IfWaterFeatures { get; set; }
        public string InAdditionalPicturesYn { get; set; }
        public int? InAdom { get; set; }
        public string InApNumber { get; set; }
        public decimal? InAssociationDues1 { get; set; }
        public decimal? InAssociationDues2 { get; set; }
        public string InAssociationFeatures { get; set; }
        public string InAssociationLitigationYn { get; set; }
        public byte? InAssociationPeriod { get; set; }
        public string InAssociationPhone { get; set; }
        public string InAssociationYn { get; set; }
        public DateTime? InCloseDate { get; set; }
        public string InCompensationBuyAgent { get; set; }
        public string InCompensationNonrep { get; set; }
        public string InCompensationTransactionAgent { get; set; }
        public string InDetailUrl { get; set; }
        public DateTime? InEscrowDate { get; set; }
        public string InExclusions { get; set; }
        public byte? InImageCount { get; set; }
        public string InLastTransactionCode { get; set; }
        public decimal? InLeaseAmount { get; set; }
        public byte? InLeasePeriod { get; set; }
        public string InLeaseOptionYn { get; set; }
        public byte? InLeaseTerm { get; set; }
        public string InLegalDescription { get; set; }
        public string InLegalFeatures { get; set; }
        public DateTime? InListDate { get; set; }
        public decimal? InListPrice { get; set; }
        public string InListPriceExclusionRemarks { get; set; }
        public string InListingAgreementType { get; set; }
        public string InListingHasForSaleSignYn { get; set; }
        public short? InListingLoadedByBroker { get; set; }
        public DateTime? InLoadDate { get; set; }
        public DateTime? InModifyDate { get; set; }
        public DateTime? InOffmarketDate { get; set; }
        public decimal? InOrigListPrice { get; set; }
        public string InOwnerName { get; set; }
        public string InOwnerPhone { get; set; }
        public DateTime? InPendingDate { get; set; }
        public decimal? InPendingPrice { get; set; }
        public decimal? InPreviousListPrice { get; set; }
        public string InPreviousStatus { get; set; }
        public DateTime? InProjectedEscrowCloseDate { get; set; }
        public string InPropertyType { get; set; }
        public string InPublicRemarks { get; set; }
        public DateTime? InPullDate { get; set; }
        public decimal? InRangeHighPrice { get; set; }
        public decimal? InRangeLowPrice { get; set; }
        public string InRangePriceFlag { get; set; }
        public string InReciprocalListing { get; set; }
        public string InRestrictions { get; set; }
        public string InSellerAgreesToPayPoints { get; set; }
        public decimal? InSellingOfficeComp { get; set; }
        public string InSellingOfficeCompType { get; set; }
        public string InSellingOfficeCompensation { get; set; }
        public string InShowingInstructions { get; set; }
        public string InSoldAgentName { get; set; }
        public string InSoldAgentOfficeId { get; set; }
        public string InSoldAgentPublicId { get; set; }
        public DateTime? InSoldDate { get; set; }
        public string InSoldFinanceTerms { get; set; }
        public string InSoldOfficeName { get; set; }
        public decimal? InSoldPrice { get; set; }
        public string InSoldTerms { get; set; }
        public string InStatus { get; set; }
        public DateTime? InStatusDate { get; set; }
        public string InSubtype { get; set; }
        public DateTime? InSystemExpireDate { get; set; }
        public decimal? InTotalAssessedValue { get; set; }
        public string InTractCode { get; set; }
        public string InTractName { get; set; }
        public DateTime? InTransactDate { get; set; }
        public string InTransferOfPossession { get; set; }
        public string InViewYn { get; set; }
        public string InVirtualTourLink { get; set; }
        public DateTime? InWithdrawnDate { get; set; }
        public string RegMlsCode { get; set; }
        public string ScElementarySchool { get; set; }
        public string ScHighSchool { get; set; }
        public string ScJuniorHighSchool { get; set; }
        public string ScSchoolDistrict { get; set; }
        public string ListOnInternetYn { get; set; }
        public string DisplayAddressYn { get; set; }
        public string ListingIddYn { get; set; }
        public string DisplayDistressedPropertyYn { get; set; }
        public string InDistressType { get; set; }
        public string ConApprovalRequirement { get; set; }
        public decimal? ConMaintenanceFee { get; set; }
        public string ConManagementFeatures { get; set; }
        public string ConMinimumLease { get; set; }
        public string ConUnitLevel { get; set; }
        public byte? ExCarportSpaces { get; set; }
        public string ExConstructionFeatures { get; set; }
        public string ExFenceFeatures { get; set; }
        public string ExFoundationFeatures { get; set; }
        public string ExGarageFeatures { get; set; }
        public short? ExGarageRemotes { get; set; }
        public byte? ExGarageSpaces { get; set; }
        public string ExGarageType { get; set; }
        public string ExGeneralFeatures { get; set; }
        public string ExGolfFeatures { get; set; }
        public string ExHorsePropertyFeatures { get; set; }
        public string ExPatioDimensions { get; set; }
        public string ExPatioFeatures { get; set; }
        public string ExPatioYn { get; set; }
        public string ExPoolFeatures { get; set; }
        public string ExPoolYn { get; set; }
        public string ExRoofFeatures { get; set; }
        public string ExRvParkingDimensions { get; set; }
        public string ExSolarFeatures { get; set; }
        public string ExSpaFeatures { get; set; }
        public string ExSpaYn { get; set; }
        public string ExSprinklerFeatures { get; set; }
        public string ExStyleFeatures { get; set; }
        public string ExSubdivisionFeatures { get; set; }
        public string ExWaterstructuresFeatures { get; set; }
        public string IfApplianceFeatures { get; set; }
        public string IfBasementFeatures { get; set; }
        public string IfCoolingFeatures { get; set; }
        public string IfCoolingYn { get; set; }
        public string IfEnergyFeatures { get; set; }
        public string IfFireplaceFeatures { get; set; }
        public byte? IfFireplaceNumber { get; set; }
        public string IfFireplaceYn { get; set; }
        public string IfFloorFeatures { get; set; }
        public string IfGeneralFeatures { get; set; }
        public string IfHeatingFeatures { get; set; }
        public string IfLevels { get; set; }
        public short? IfNumberCeilingFans { get; set; }
        public string IfPetFeatures { get; set; }
        public string IfPlumbingFeatures { get; set; }
        public string IfSecurityFeatures { get; set; }
        public string IfSecuritySystemYn { get; set; }
        public string IfWindowFeatures { get; set; }
        public string InAdditionsAlterYn { get; set; }
        public string InAgeFeatures { get; set; }
        public string InBuilderName { get; set; }
        public string InIsAttached { get; set; }
        public string InKeyboxFeatures { get; set; }
        public string InKeyboxLocation { get; set; }
        public int? InLivingSquareFeet { get; set; }
        public string InModelName { get; set; }
        public DateTime? InRemodeledDate { get; set; }
        public short? InTotalUnitsInComplex { get; set; }
        public string InVolt220OutletLocation { get; set; }
        public short? InYearBuilt { get; set; }
        public string LeAssociationDuesIncYn { get; set; }
        public string LeCableIncYn { get; set; }
        public string LeElectricIncYn { get; set; }
        public string LeFurnishedYn { get; set; }
        public string LeGardnerIncYn { get; set; }
        public string LeGasIncYn { get; set; }
        public string LeMaidIncYn { get; set; }
        public string LeMoToMoYn { get; set; }
        public string LePetsYn { get; set; }
        public string LePoolIncYn { get; set; }
        public string LeTrashIncYn { get; set; }
        public string LeWaterIncYn { get; set; }
        public string RmBathroomFeatures { get; set; }
        public byte? RmBathsFull { get; set; }
        public byte? RmBathsHalf { get; set; }
        public byte? RmBathsQuarter { get; set; }
        public byte? RmBathsThreeQuarter { get; set; }
        public decimal? RmBathsTotal { get; set; }
        public string RmBedroomFeatures { get; set; }
        public byte? RmBedroomsTotal { get; set; }
        public string RmBonusFeatures { get; set; }
        public string RmBonusYn { get; set; }
        public string RmConvertedBedroomYn { get; set; }
        public string RmDenYn { get; set; }
        public string RmDiningFeatures { get; set; }
        public string RmFamilyYn { get; set; }
        public string RmFormalDiningYn { get; set; }
        public string RmGeneralFeatures { get; set; }
        public string RmKitchenFeatures { get; set; }
        public string RmLaundryFeatures { get; set; }
        public string RmLivingFeatures { get; set; }
        public string RmLivingYn { get; set; }
        public string RmMasterDressingAreaYn { get; set; }
        public string RmMasterYn { get; set; }
        public string RmRoom1Features { get; set; }
        public string RmRoom1Type { get; set; }
        public string RmRoom1Dimensions1 { get; set; }
        public string RmRoom1Dimensions2 { get; set; }
        public string RmRoom2Features { get; set; }
        public string RmRoom2Type { get; set; }
        public string RmRoom2Dimensions1 { get; set; }
        public string RmRoom2Dimensions2 { get; set; }
        public string RmRoom3Features { get; set; }
        public string RmRoom3Type { get; set; }
        public string RmRoom3Dimensions1 { get; set; }
        public string RmRoom3Dimensions2 { get; set; }
        public string RmRoom4Features { get; set; }
        public string RmRoom4Type { get; set; }
        public string RmRoom4Dimensions1 { get; set; }
        public string RmRoom4Dimensions2 { get; set; }
        public string RmRoom5Features { get; set; }
        public string RmRoom5Type { get; set; }
        public string RmRoom5Dimensions1 { get; set; }
        public string RmRoom5Dimensions2 { get; set; }
        public string RmRoom6Features { get; set; }
        public string RmRoom6Type { get; set; }
        public string RmRoom6Dimensions1 { get; set; }
        public string RmRoom6Dimensions2 { get; set; }
        public string RmRoom7Features { get; set; }
        public string RmRoom7Type { get; set; }
        public string RmRoom7Dimensions1 { get; set; }
        public string RmRoom7Dimensions2 { get; set; }
        public string RmRoom8Features { get; set; }
        public string RmRoom8Type { get; set; }
        public string RmRoom8Dimensions1 { get; set; }
        public string RmRoom8Dimensions2 { get; set; }
        public string RmRoom9Features { get; set; }
        public string RmRoom9Type { get; set; }
        public string RmRoom9Dimensions1 { get; set; }
        public string RmRoom9Dimensions2 { get; set; }
        public string RmRoom10Features { get; set; }
        public string RmRoom10Type { get; set; }
        public string RmRoom10Dimensions1 { get; set; }
        public string RmRoom10Dimensions2 { get; set; }
        public string RmRoom11Features { get; set; }
        public string RmRoom11Type { get; set; }
        public string RmRoom11Dimensions1 { get; set; }
        public string RmRoom11Dimensions2 { get; set; }
        public string RmRoom12Features { get; set; }
        public string RmRoom12Type { get; set; }
        public string RmRoom12Dimensions1 { get; set; }
        public string RmRoom12Dimensions2 { get; set; }
        public string RmRoom13Features { get; set; }
        public string RmRoom13Type { get; set; }
        public string RmRoom13Dimensions1 { get; set; }
        public string RmRoom13Dimensions2 { get; set; }
        public string RmRoom14Features { get; set; }
        public string RmRoom14Type { get; set; }
        public string RmRoom14Dimensions1 { get; set; }
        public string RmRoom14Dimensions2 { get; set; }
        public int? RmRoomsTotal { get; set; }
        public string RmTermiteClearYn { get; set; }
        public string RmUtilityFeatures { get; set; }
        public byte? RmWalkInClosets { get; set; }
        public int? InRangeHighLivingSquareFeet { get; set; }
        public int? InRangeLowLivingSquareFeet { get; set; }
        public int? PublishStatus { get; set; }
        public DateTimeOffset LastUpdate { get; set; }
        public int LastImport { get; set; }
    }
}
